name: Python CI with Coverage

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      # Ejecutar pruebas con cobertura y generar reporte HTML
      - name: Run tests with coverage and generate HTML report
        run: pytest tests/ --cov=. --cov-report=html --cov-report=xml

      # Subir el reporte HTML como artefacto
      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v3
        with:
          name: html-coverage-report
          path: htmlcov
